apiVersion: operator.openshift.io/v1alpha1
kind: SpireOIDCDiscoveryProvider
metadata:
  name: cluster
spec:
  logLevel: info
  logFormat: text
  jwtIssuer: {{ .Values.global.jwtIssuer | quote }}
  csiDriverName: "csi.spiffe.io"
  replicaCount: 1
  managedRoute: "true"
