apiVersion: operator.openshift.io/v1alpha1
kind: ZeroTrustWorkloadIdentityManager
metadata:
  name: cluster
spec:
  trustDomain: {{ .Values.ztwim.trustDomain | quote }}
  clusterName: {{ .Values.ztwim.clusterName | quote }}
