minio:
  enabled: true
  fullnameOverride: minio
  nameOverride: minio
  configPathmc: "/tmp/minio/mc/"
  mode: standalone
  persistence:
    size: 5Gi
  securityContext:
    runAsUser: null
    runAsGroup: null
    fsGroup: null
    fsGroupChangePolicy: null
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
  users: []
  buckets:
    - name: tempo-traces
      policy: none
      purge: false
    - name: loki-chunks
      policy: none
      purge: false
    - name: loki-ruler
      policy: none
      purge: false
    - name: loki-admin
      policy: none
      purge: false
  postJob:
    annotations:
      argocd.argoproj.io/sync-wave: "1"