apiVersion: v2
name: lgtm
description: A Helm chart for Kubernetes
type: application
version: 0.1.0

dependencies:
  - alias: grafana
    condition: grafana.enabled
    name: grafana
    repository: https://grafana.github.io/helm-charts
    version: 10.3.0
  - alias: loki
    condition: loki.enabled
    name: loki
    repository: https://grafana.github.io/helm-charts
    version: 6.48.0
  - alias: tempo
    condition: tempo.enabled
    name: tempo
    repository: https://grafana.github.io/helm-charts
    version: 1.24.1
  - alias: mimir
    condition: mimir.enabled
    name: mimir-distributed
    repository: file://mimir
    version: 5.9.0-weekly.365
  - alias: opentelemetry-collector
    condition: opentelemetry-collector.enabled
    name: opentelemetry-collector
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
    version: 0.142.2
  - alias: prometheus
    condition: prometheus.enabled
    name: prometheus
    repository: https://prometheus-community.github.io/helm-charts
    version: 25.30.1
