quarkus.mcp.server.server-info.name=Globex Store API
quarkus.mcp.server.server-info.version=1.0
quarkus.mcp.server.traffic-logging.enabled=true
quarkus.mcp.server.traffic-logging.text-limit=1000

# otel
quarkus.otel.enabled=true
quarkus.otel.logs.enabled=true
quarkus.otel.traces.enabled=true
quarkus.otel.metrics.enabled=false

# Micrometer and Prometheus metrics configuration
quarkus.micrometer.enabled=true
quarkus.micrometer.binder-enabled-default=true
quarkus.micrometer.binder.http-server.enabled=true
quarkus.micrometer.binder.http-client.enabled=true
quarkus.micrometer.binder.jvm=true
quarkus.micrometer.export.prometheus.enabled=true
quarkus.micrometer.export.prometheus.path=/q/metrics