quarkus.mcp.server.server-info.name=Globex Store API
quarkus.mcp.server.server-info.version=1.0
quarkus.mcp.server.traffic-logging.enabled=true
quarkus.mcp.server.traffic-logging.text-limit=1000

# otel
quarkus.otel.enabled=true
quarkus.otel.logs.enabled=true
quarkus.otel.traces.enabled=true
quarkus.otel.metrics.enabled=true



quarkus.log.category."io.quarkus.oidc".level=DEBUG
quarkus.log.category."io.quarkus.oidc-client".level=DEBUG
