# Database configuration
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${POSTGRESQL_USER}
quarkus.datasource.password=${POSTGRESQL_PASSWORD}
quarkus.datasource.jdbc.url=jdbc:postgresql://${POSTGRESQL_HOST}:${POSTGRESQL_PORT:5432}/${POSTGRESQL_DATABASE}

# Hibernate ORM configuration
%dev.quarkus.datasource.devservices.enabled=false
%dev.quarkus.hibernate-orm.schema-management.strategy=validate
%dev.quarkus.hibernate-orm.log.sql=true
