# Database configuration
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${POSTGRESQL_USER}
quarkus.datasource.password=${POSTGRESQL_PASSWORD}
quarkus.datasource.jdbc.url=jdbc:postgresql://${POSTGRESQL_HOST}:${POSTGRESQL_PORT:5432}/${POSTGRESQL_DATABASE}

# MCP Server configuration
quarkus.mcp.server.http.root-path=/mcp
quarkus.mcp.server.server-info.name=Globex Complaints
quarkus.mcp.server.server-info.version=1.0
quarkus.mcp.server.traffic-logging.enabled=true
quarkus.mcp.server.traffic-logging.text-limit=1000

# OIDC Configuration for Service Account Authentication
quarkus.oidc.auth-server-url=${KEYCLOAK_URL}/realms/${KEYCLOAK_REALM:master}

# Accept Bearer tokens for service-to-service auth
quarkus.oidc.application-type=service

# Secure MCP endpoints
quarkus.http.auth.permission.mcp.paths=/mcp/*
quarkus.http.auth.permission.mcp.policy=authenticated

# Setup the READ mcp server configuration and permissions
quarkus.mcp.server.read.http.root-path=/read/mcp
quarkus.mcp.server.read.server-info.name=Globex Complaints Read Operations
quarkus.mcp.server.read.server-info.version=1.0
quarkus.mcp.server.read.traffic-logging.enabled=true
quarkus.mcp.server.read.traffic-logging.text-limit=1000

quarkus.http.auth.permission.read.paths=/read/mcp/*
quarkus.http.auth.permission.read.policy=permit

# otel
quarkus.otel.enabled=true
quarkus.otel.logs.enabled=true
quarkus.otel.traces.enabled=true
quarkus.otel.metrics.enabled=true

# Hibernate ORM configuration
%dev.quarkus.datasource.devservices.enabled=false
%dev.quarkus.hibernate-orm.schema-management.strategy=validate
%dev.quarkus.hibernate-orm.log.sql=true

# dev
%dev.quarkus.otel.enabled=false
