apiVersion: v1
kind: Secret
metadata:
  name: {{ include "globex-complaints.name" . }}
  labels:
    {{- include "globex-complaints.labels" . | nindent 4 }}
  annotations:
    {{- include "globex-complaints.argocd-syncwave" . | nindent 4 }}
type: "Opaque"
stringData:
  application.properties: |-

    quarkus.otel.exporter.otlp.endpoint={{ .Values.otel.exporter.endpoint }}
