keycloak-realmimport-mcp:
  argocd:
    enabled: true
    syncwave: "-2"

keycloak-realmimport-globex:
  argocd:
    enabled: true
    syncwave: "-2"

kafka-broker:
  argocd:
    enabled: true
    syncwave: "-1"

kafka-topics:
  argocd:
    enabled: true
    syncwave: "-1"

globex-db:
  argocd:
    enabled: true
    syncwave: "-1"

globex-store-app:
  argocd:
    enabled: true
    syncwave: "0"

globex-web:
  argocd:
    enabled: true
    syncwave: "1"

activity-tracking:
  argocd:
    enabled: true
    syncwave: "1"

recommendation-engine:
  argocd:
    enabled: true
    syncwave: "1"

globex-store-mcp:
  argocd:
    enabled: true
    syncwave: "1"

globex-complaints:
  argocd:
    enabled: true
    syncwave: "1"

globex-agent:
  argocd:
    enabled: true
    syncwave: "2"
