quarkus.oidc.application-type=service

quarkus.datasource.db-kind=postgresql
quarkus.hibernate-orm.mapping.format.global=ignore

quarkus.langchain4j.response-schema=false

quarkus.langchain4j.chat-model.provider=openai
quarkus.langchain4j.openai.routing.log-requests=true
quarkus.langchain4j.openai.routing.log-responses=true
quarkus.langchain4j.openai.routing.chat-model.temperature=0.1
quarkus.langchain4j.openai.routing.timeout=180s

quarkus.langchain4j.openai.complaint.log-requests=true
quarkus.langchain4j.openai.complaint.log-responses=true
quarkus.langchain4j.openai.complaint.chat-model.temperature=0.1
quarkus.langchain4j.openai.complaint.timeout=180s

quarkus.langchain4j.openai.order.log-requests=true
quarkus.langchain4j.openai.order.log-responses=true
quarkus.langchain4j.openai.order.chat-model.temperature=0.1
quarkus.langchain4j.openai.order.timeout=180s

quarkus.langchain4j.mcp.generate-tool-provider=false
quarkus.langchain4j.mcp."globex-store".transport-type=streamable-http
quarkus.langchain4j.mcp."complaints".transport-type=streamable-http
quarkus.langchain4j.mcp.health.enabled=false

aiservice."identify-need".temperature=0.3
aiservice."handle-other".temperature=0.3
aiservice."classify-intent".temperature=0.1
aiservice."lookup-order-history".temperature=0.3
aiservice."product_selection".temperature=0.1
aiservice."product_not_selected".temperature=0.3
aiservice."complaint".temperature=0.3
aiservice."order".temperature=0.3

# otel
quarkus.otel.enabled=true
quarkus.otel.logs.enabled=true
quarkus.otel.traces.enabled=true
quarkus.otel.metrics.enabled=true

# otel dev
%dev.quarkus.otel.enabled=false

%dev.quarkus.oidc.devservices.enabled=false
%dev.quarkus.datasource.devservices.enabled=false
%dev.quarkus.hibernate-orm.schema-management.strategy=validate
%dev.quarkus.hibernate-orm.log.sql=true
