quarkus.oidc.application-type=service

quarkus.datasource.db-kind=postgresql
quarkus.hibernate-orm.mapping.format.global=ignore

%dev.quarkus.oidc.devservices.enabled=false
%dev.quarkus.datasource.devservices.enabled=false
%dev.quarkus.hibernate-orm.schema-management.strategy=validate
%dev.quarkus.hibernate-orm.log.sql=true
