---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: "{{ include "ztwim-operator.name" . }}-operatorgroup"
  namespace: {{ include "ztwim-operator.namespace" . }}
  annotations:
    {{- include "ztwim-operatorgroup.argocd-syncwave" . | nindent 4 }}
spec:
  targetNamespaces:
    - {{ include "ztwim-operator.namespace" . }}
