global:
  kafka:
    name: &kafka kafka
    namespace: &kafkanamespace kafka
    kafka-cluster: &kafkacluster
      bootstrapServer: kafka-kafka-bootstrap.kafka.svc.cluster.local:9092
      securityProtocol: SASL_PLAINTEXT
      saslMechanism: SCRAM-SHA-512
      clientId: globex
      clientSecret: globex

amqstreams:
  enabled: true
  applicationName: amqstreams
  applicationNamespace: openshift-gitops
  destinationNamespace: kafka
  source:
    repoUrl: https://github.com/quarkus-mcp-demo/mcp-demo-poc.git
    targetRevision: oidc-0.1
    path: install/helm/amq-streams
    helm:
      values:
        kafka:
          enabled: true
        console:
          enabled: true

        kafka-broker:
          namespace: *kafkanamespace
          nameOverride: *kafka
          kafka:
            controller:
              enabled: true
            listener:
              external:
                tls:
                  secret:
                    value:
                      crt: 
                      key: 
          authentication:
            clientId: admin
            clientSecret: adminpassword
            securityProtocol: SASL_PLAINTEXT
            saslMechanism: SCRAM-SHA-512
        amq-streams-console:
          namespace: *kafkanamespace
          subdomain: 
          kafka:
            name: *kafka
            namespace: *kafkanamespace
            authentication:
              securityProtocol: SASL_SSL
              saslMechanism: SCRAM-SHA-512
            authorization: simple
        kafka-topics:
          kafka:
            namespace: *kafkanamespace
            cluster: *kafka
  argocd:
    enabled: true
    syncwave: "1"

keycloak:
  enabled: true
  applicationName: keycloak
  applicationNamespace: openshift-gitops
  destinationNamespace: keycloak
  source:
    repoUrl: https://github.com/quarkus-mcp-demo/mcp-demo-poc.git
    targetRevision: oidc-0.1
    path: install/helm/keycloak
    helm:
      values:
        keycloak:
          nameOverride: keycloak
          route:
            host:
          ingress:
            enabled: false
  argocd:
    enabled: true
    syncwave: "1"

globex:
  enabled: true
  applicationName: globex
  applicationNamespace: openshift-gitops
  destinationNamespace: globex
  source:
    repoUrl: https://github.com/quarkus-mcp-demo/mcp-demo-poc.git
    targetRevision: oidc-0.1
    path: install/helm/globex
    helm:
      values:
        kafka-broker:
          namespace: *kafkanamespace
          nameOverride: *kafka

        kafka-topics:
          kafka:
            namespace: *kafkanamespace
            cluster: *kafka
        globex-db:
          pgsql:
            adminPassword: adminpassword

        keycloak-realmimport-globex:
          namespace: keycloak
          keycloak:
            name: keycloak
          realm:
            name: globex
          client:
            gateway:
              name: globex-web-gateway

        globex-web:
          sso:
            authServer:
            realm: globex
            client: globex-web-gateway
          subdomain:

        activity-tracking:
          kafka:
            <<: *kafkacluster

        recommendation-engine:
          kafka:
            <<: *kafkacluster

        globex-agent:
          oidc:
            realm: globex
            clientId: globex-web-gateway
          mcp:
            globexStore:
              url: http://globex-store-mcp:8080/mcp
              logRequests: true
              logResponses: true
            complaints:
              url: http://globex-complaints:8080/mcp
              logRequests: true
              logResponses: true
          otel:
            exporter:
              endpoint: http://otel.lgtm.svc.cluster.local:4317

        globex-complaints:
          otel:
            exporter:
              endpoint: http://otel.lgtm.svc.cluster.local:4317

        globex-store-mcp:
          otel:
            exporter:
              endpoint: http://otel.lgtm.svc.cluster.local:4317

  argocd:
    enabled: true
    syncwave: "3"

lgtm:
  enabled: true
  applicationName: lgtm
  applicationNamespace: openshift-gitops
  destinationNamespace: lgtm
  source:
    repoUrl: https://github.com/quarkus-mcp-demo/mcp-demo-poc.git
    targetRevision: oidc-0.1
    path: install/helm/lgtm
    helm:
      values:
        grafana:
          route:
            host:
        tempo:
          tempo:
            storage:
              trace:
                s3:
                  access_key:
                  secret_key:
        mimir:
          minio:
            rootUser: 
            rootPassword:
        loki:
          loki:
            storage:
              type: s3
              s3:
                access_key_id: 
                secret_access_key: 

  argocd:
    enabled: true
    syncwave: "2"

minio:
  enabled: true
  applicationName: minio
  applicationNamespace: openshift-gitops
  destinationNamespace: lgtm
  source:
    repoUrl: https://github.com/quarkus-mcp-demo/mcp-demo-poc.git
    targetRevision: oidc-0.1
    path: install/helm/minio
    helm:
      values:
        minio:
          rootUser:
          rootPassword: 
          securityContext:
            enabled: false
  argocd:
    enabled: true
    syncwave: "1"
