nameOverride: "ztwim"
fullnameOverride: ""

namespace: "openshift-operators"

ztwim:
  subscription:
    channel: stable-v1
    installPlanApproval: Automatic
    name: openshift-zero-trust-workload-identity-manager
    source: redhat-operators
    sourceNamespace: openshift-marketplace

argocd:
  enabled: true
  operatorgroup:
    syncwave: "-3"
  operator:
    syncwave: "-2"
