apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "globex-agent.name" . }}
  labels:
    {{- include "globex-agent.labels" . | nindent 4 }}
    app.openshift.io/runtime: quarkus
  annotations:
    {{- include "globex-agent.argocd-syncwave" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "globex-agent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "globex-agent.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "globex-agent.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.containerPort }}
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: POSTGRESQL_USERNAME
              valueFrom:
                secretKeyRef:
                  key: database-user
                  name: {{ .Values.globexDb.secret.name }}
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: database-password
                  name: {{ .Values.globexDb.secret.name }}
            - name: POSTGRESQL_DATABASE
              valueFrom:
                secretKeyRef:
                  key: database-name
                  name: {{ .Values.globexDb.secret.name }}
            - name: POSTGRESQL_HOST
              value: {{ .Values.globexDb.name }}
            - name: POSTGRESQL_PORT
              value: '5432'
            - name: QUARKUS_DATASOURCE_USERNAME
              value: ${POSTGRESQL_USERNAME}
            - name: QUARKUS_DATASOURCE_PASSWORD
              value: ${POSTGRESQL_PASSWORD}
            - name: QUARKUS_DATASOURCE_JDBC_URL
              vallue: jdbc:postgresql://${POSTGRESQL_HOST}:${POSTGRESQL_PORT}/${POSTGRESQL_DATABASE}
          volumeMounts:
            - mountPath: /deployments/config
              name: config
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: config
          secret:
            secretName: {{ include "globex-agent.name" . }}
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
