apiVersion: v1
kind: Secret
metadata:
  name: {{ include "globex-agent.name" . }}
  labels:
    {{- include "globex-agent.labels" . | nindent 4 }}
  annotations:
    {{- include "globex-agent.argocd-syncwave" . | nindent 4 }}
type: "Opaque"
stringData:
  application.properties: |-

    quarkus.oidc.auth-server-url={{ .Values.oidc.authServerUrl }}/realms/{{ .Values.oidc.realm }}
    quarkus.oidc.client-id={{ .Values.oidc.clientId }}
    quarkus.oidc.credentials.client-secret.value={{ .Values.oidc.clientSecret }}

    quarkus.langchain4j.openai.chat-model.model-name={{ .Values.llm.routing.modelName }}
    quarkus.langchain4j.openai.api-key={{ .Values.llm.routing.apiKey }}
    quarkus.langchain4j.openai.base-url={{ .Values.llm.routing.baseUrl }}

    quarkus.langchain4j.openai.routing.chat-model.model-name={{ .Values.llm.routing.modelName }}
    quarkus.langchain4j.openai.routing.api-key={{ .Values.llm.routing.apiKey }}
    quarkus.langchain4j.openai.routing.base-url={{ .Values.llm.routing.baseUrl }}

    quarkus.langchain4j.openai.complaint.chat-model.model-name={{ .Values.llm.complaint.modelName }}
    quarkus.langchain4j.openai.complaint.api-key={{ .Values.llm.complaint.apiKey }}
    quarkus.langchain4j.openai.complaint.base-url={{ .Values.llm.complaint.baseUrl }}

    quarkus.langchain4j.openai.order.chat-model.model-name={{ .Values.llm.order.modelName }}
    quarkus.langchain4j.openai.order.api-key={{ .Values.llm.order.apiKey }}
    quarkus.langchain4j.openai.order.base-url={{ .Values.llm.order.baseUrl }}

    quarkus.langchain4j.mcp."globex-store".url={{ .Values.mcp.globexStore.url }}
    quarkus.langchain4j.mcp."globex-store".log-requests={{ .Values.mcp.globexStore.logRequests }}
    quarkus.langchain4j.mcp."globex-store".log-responses={{ .Values.mcp.globexStore.logResponses }}

    quarkus.langchain4j.mcp."complaints".url={{ .Values.mcp.complaints.url }}
    quarkus.langchain4j.mcp."complaints".log-requests={{ .Values.mcp.complaints.logRequests }}
    quarkus.langchain4j.mcp."complaints".log-responses={{ .Values.mcp.complaints.logResponses }}     

    quarkus.http.cors.enabled={{ .Values.cors.enabled }}
    quarkus.http.cors.origins= {{ .Values.cors.origins }}
    quarkus.http.cors.methods={{ .Values.cors.methods }}

    quarkus.otel.exporter.otlp.endpoint={{ .Values.otel.exporter.endpoint }}
    quarkus.otel.exporter.otlp.metrics.endpoint={{ .Values.otel.exporter.endpoint }}


    #OIDC Setup for Globex Agent to call MCP and Complaints service
    quarkus.oidc-client.auth-server-url={{ .Values.oidc.authServerUrl }}/realms/{{ .Values.oidc.realm }}

    quarkus.oidc-client.complaints.auth-server-url={{ .Values.oidc.authServerUrl }}/realms/{{ .Values.oidc.realm }}
    quarkus.oidc-client.complaints.client-id={{ .Values.oidc.complaints.clientId }}
    quarkus.oidc-client.complaints.credentials.secret={{ .Values.oidc.complaints.secret }}

    quarkus.oidc-client.globex-store.auth-server-url={{ .Values.oidc.authServerUrl }}/realms/{{ .Values.oidc.realm }}
    quarkus.oidc-client.globex-store.client-id={{ .Values.oidc.globexStoreMcp.clientId }}
    quarkus.oidc-client.globex-store.credentials.secret={{ .Values.oidc.globexStoreMcp.clientSecret }}